<?php
$fileExist = Mage::getModel('catalog/product')->checkProductCheckLogFileExistOrNot();
if ($fileExist):
    echo Mage::helper('epicor_comm')->__('Processing is already in progress. Please use Epicor > Advanced > System Logs to view ‘productcheck.log’.');
else:
    echo Mage::helper('epicor_comm')->__('This procedure will create a csv file containing a list of all group products that have duplicates.<br><br>');
    echo Mage::helper('epicor_comm')->__('Once you have clicked proceed, you can close this page. <br><br>');
    echo Mage::helper('epicor_comm')->__('Depending upon the number of products in your database, this process may take some time.<br><br>');
    echo Mage::helper('epicor_comm')->__('You can check processing progress using Epicor > Advanced > System Logs and viewing ‘productcheck.log’.<br><br>');
    echo Mage::helper('epicor_comm')->__('When processing is complete,  productcheck.log will no longer be available and there will be a date stamped 
file called WSO-5995-yymmddhhmmss.csv which you can download and view.<br><br>');
    ?>
    <div id="hideclassdownloadbutton">
        <?php
        echo Mage::helper('epicor_comm')->__('Click proceed to continue');
        ?>
        <input type="button" id="createcsv" class="btn" value="<?php echo Mage::helper('epicor_comm')->__('Proceed'); ?>" />
    </div>
    <span id="downloadtext"></span>
    <script type="text/javascript">
        $('createcsv').observe('click', function () {
            new Ajax.Request("<?php echo Mage::getUrl('comm/test/groupproductcsv') ?>", {
                parameters: {isAjax: 1, method: 'GET'},
                onSuccess: function (transport) {
                    $('createcsv').disable();
                    if (transport.responseText === "error") {
                        alert("<?php echo Mage::helper('epicor_comm')->__("Sorry!! You don't have enough privileges to access the requested page."); ?>");
                        $('hideclassdownloadbutton').show();
                        $('downloadtext').update("");
                        $('createcsv').show();
                        $('createcsv').removeAttribute('disabled');
                    } else if (transport.responseText === "success") {
                        $('hideclassdownloadbutton').hide();
                        $('downloadtext').update("");
                        $('downloadtext').update("<?php echo Mage::helper('epicor_comm')->__('Processing'); ?>");
                        $('downloadtext').setStyle({fontWeight: 'bold', fontSize: '21px'});
                        $('download').hide();
                        $('createcsv').value = "<?php echo Mage::helper('epicor_comm')->__('Processing'); ?>";
                    }

                }
            });
        });
    </script>
<?php endif; ?>
