<?php if ($this->getCheckout()->getStepData('salesrep_contact', 'is_show')): ?>
    <div id="salesrep_contact-progress-opcheckout">
        <?php if ($this->isStepComplete('salesrep_contact')): ?>     
            <dt class="complete">
            <?php echo $this->__('ERP Contact') ?> 
            </dt>
            <dd class="complete">
                <?php echo $this->getSalesrepCustomerName(); ?>
                <?php if ($this->getSalesrepCustomerEmail()) : ?>
                    (<?php echo $this->getSalesrepCustomerEmail(); ?>)
                <?php endif; ?>
            </dd>
        <?php else: ?>
            <dt>
            <?php echo $this->__('ERP Contact') ?>
            </dt>
        <?php endif; ?>
    </div>
<?php endif; ?>