<?php
/**
 * Template for block Epicor_Comm_Block_Adminhtml_Customer_Group_Edit_Erpinfo
 */
?>
<?php
$erpCustomer = $this->getErpCustomer();
$yesNoOptions =  Mage::getModel('epicor_comm/config_source_yesnonulloption')->toOptionArray();
$yesNoBranchOptions = Mage::getModel('epicor_branchpickup/config_source_branchoptions')->toOptionArray();
$eccDisableFunctionalityOption = Mage::getModel('epicor_comm/config_source_eccdisablefunctionalityoptions')->toOptionArray();
$arpaymentOptions =  Mage::getModel('customerconnect/config_source_arpayments')->toOptionArray();
$accountType = $erpCustomer->getAccountType();
?>
<div class="entry-edit box-left" style="width:49.5%">
    <div class="entry-edit-head"><h4 class="icon-head head-customer-view"><?php echo Mage::helper('epicor_comm')->__('ERP Group Information') ?></h4></div>
    <fieldset class="erp_infomation">
        <table>
            <tr>
                <td class="label"><strong><?php echo $this->__('Company:') ?></strong></td>
                <td><?php echo $erpCustomer->getCompany() ?></td>
            </tr>
            <tr>
                <td class="label"><strong><?php echo $this->__('Short Code:') ?></strong></td>
                <td><?php echo $erpCustomer->getShortCode() ?></td>
            </tr>
            <tr>
                <td class="label"><strong><?php echo $this->__('ERP Account Number:') ?></strong></td>
                <td><?php echo $erpCustomer->getAccountNumber() ?></td>
            </tr>
            <tr>
                <td class="label"><strong><?php echo $this->__('Name:') ?></strong></td>
                <td><?php echo $erpCustomer->getName() ?></td>
            </tr>
<!--            <tr>
                <td class="label"><strong><?php echo $this->__('Credit Limit:') ?></strong></td>
                <td><?php echo $erpCustomer->getCreditLimit() ?></td>
            </tr>
            <tr>
                <td class="label"><strong><?php echo $this->__('Current Balance:') ?></strong></td>
                <td><?php echo $erpCustomer->getBalance() ?></td>
            </tr>
            <tr>
                <td class="label"><strong><?php echo $this->__('On Stop:') ?></strong></td>
                <td><?php echo $erpCustomer->getOnStop() ? 'True' : 'False' ?></td>
            </tr>
            <tr>
                <td class="label"><strong><?php echo $this->__('Min Order Amount:') ?></strong></td>
                <td><?php echo $erpCustomer->getMinOrderAmount() ?></td>
            </tr>-->
            <tr>
                <td class="label"><strong><?php echo $this->__('Is Default Customer:') ?></strong></td>
                <td><?php echo Mage::getStoreConfig('customer/create_account/default_erpaccount') == $erpCustomer->getEntityId() ? 'True' : 'False' ?></td>
            </tr>
            <tr>
                <td class="label"><strong><?php echo $this->__('Linked Customer Group:') ?></strong></td>
                <td><?php echo $this->getCustomerGroup()->getCustomerGroupCode(); ?></td>
            </tr>
            <?php if($erpCustomer->getDefaultPaymentMethodCode()){ ?>
            <tr>
                <td class="label"><strong><?php echo $this->__('Default Payment Method Code:') ?></strong></td>
                <td><?php echo $erpCustomer->getDefaultPaymentMethodCode(); ?></td>
            </tr>
            <?php } ?>
            <?php if($erpCustomer->getDefaultDeliveryMethodCode()){ ?>
            <tr>
                <td class="label"><strong><?php echo $this->__('Default Delivery Method Code:') ?></strong></td>
                <td><?php echo $erpCustomer->getDefaultDeliveryMethodCode(); ?></td>
            </tr>
            <?php } ?>
            <tr>
                <td class="label"><strong><label for="warranty_customer"><?php echo $this->__('Warranty Customer?') ?></label></td>
                <td><input name="is_warranty_customer" id="warranty_customer" type="checkbox" <?php if ($erpCustomer->getIsWarrantyCustomer()) : ?>checked="checked"<?php endif; ?> value="1"/></td>
            </tr>
            <tr>
                <td class="label"><strong><label for="warranty_customer"><?php echo $this->__('Allow Backorders') ?></label></td>
                <td><input name="allow_backorders" id="allow_backorders" type="checkbox" <?php if ($erpCustomer->getAllowBackorders()) : ?>checked="checked"<?php endif; ?> value="1"/></td>
            </tr>
            <tr>
                <td class="label"><strong><label for="is_tax_exempt"><?php echo $this->__('Allow Tax Exempt') ?></label></td>
                <td>
                    <select name="is_tax_exempt" id="is_tax_exempt">
                        <?php foreach ($yesNoOptions as $key => $value): ?>
                            <option value="<?php echo $value['value'] ?>" <?php if ($erpCustomer->getIsTaxExempt() == $value['value']) : ?>selected="selected"<?php endif; ?>><?php echo $value['label'] ?></option>
                        <?php endforeach; ?>
                    </select>
                </td>
            </tr>
            <tr>
                <td class="label"><strong><label for="is_invoice_edit"><?php echo $this->__('Invoice Selection Is Supported') ?></label></td>
                <td>
                    <select name="is_invoice_edit" id="is_invoice_edit">
                        <?php foreach ($yesNoOptions as $key => $value): ?>
                            <option value="<?php echo $value['value'] ?>" <?php if ($erpCustomer->getIsInvoiceEdit() == $value['value']) : ?>selected="selected"<?php endif; ?>><?php echo $value['label'] ?></option>
                        <?php endforeach; ?>
                    </select>
                </td>
            </tr>
            <?php /* CPN EDITING REMOVED UNTIL IS COMPLETE
            <tr>
                <td class="label"><strong><label for="cpn_editing"><?php echo $this->__('CPN Editing') ?></label></td>
                <td>
                    <select name="cpn_editing" id="cpn_editing">
                        <?php foreach ($yesNoOptions as $key => $value): ?>
                            <option value="<?php echo $value['value'] ?>" <?php if ($erpCustomer->getCpnEditing() == $value['value']) : ?>selected="selected"<?php endif; ?>><?php echo $value['label'] ?></option>
                        <?php endforeach; ?>
                    </select>
                </td>
                    
                    <input  type="checkbox" <?php if ($erpCustomer->getIsWarrantyCustomer()) : ?>checked="checked"<?php endif; ?> value="1"/>
            </tr>
             */ ?>
            <tr>
                <td class="label"><strong><label for="po_mandatory"><?php echo $this->__('Purchase Order Number Mandatory?') ?></label></td>
                <td>
                    <select name="po_mandatory" id="po_mandatory">
                        <?php foreach ($yesNoOptions as $key => $value): ?>
                            <option value="<?php echo $value['value'] ?>" <?php if ($erpCustomer->getPoMandatory() == $value['value']) : ?>selected="selected"<?php endif; ?>><?php echo $value['label'] ?></option>
                        <?php endforeach; ?>
                    </select>
                </td>
            </tr>
            <tr>
                <td class="label"><strong><label for="erp_default_location"><?php echo $this->__('Default Location') ?></label></td>
                <td>
                    <?php $locations = Mage::getModel('epicor_comm/location')->getCollection(); ?>
                    <?php if(count($locations) < 2): ?>
                        <td><?php echo $erpCustomer->getAccountNumber() ?></td>
                    <?php else: ?>
                            <select name="erp_default_location" id="erp_default_location">

                                <option value=""></option>
                                <?php foreach ($locations as $key => $location): ?>
                                    <option value="<?php echo $location->getCode(); ?>" <?php if ($erpCustomer->getDefaultLocationCode() == $location->getCode()) : ?>selected="selected"<?php endif; ?>><?php echo $location->getCode(); ?></option>
                                <?php endforeach; ?>
                            </select>
                    <?php endif; ?>
                </td>                    
            </tr>
            <?php if($accountType !="Supplier"): ?>
            <tr>
                <td class="label"><strong><label for="is_branch_pickup_allowed"><?php echo $this->__('Branch Pickup Allowed') ?></label></td>
                    <td>
                    <select name="is_branch_pickup_allowed" id="is_branch_pickup_allowed">
                        <?php foreach ($yesNoBranchOptions as $key => $value): ?>
                            <option value="<?php echo $value['value'] ?>" <?php if ($erpCustomer->getIsBranchPickupAllowed() == $value['value']) : ?>selected="selected"<?php endif; ?>><?php echo $value['label'] ?></option>
                        <?php endforeach; ?>
                    </select>
                </td>
                </tr>
            <?php endif; ?>
                <tr>
                    <td class="label"><strong><label for="ecc_disable_functionality"><?php echo $this->__('Disable Functionality') ?></label></td>
                    <td>
                        <select name="disable_functionality" id="disable_functionality">
                            <?php foreach ($eccDisableFunctionalityOption as $key => $value): ?>
                                <option value="<?php echo $value['value'] ?>" <?php if ($erpCustomer->getDisableFunctionality() == $value['value']) : ?>selected="selected"<?php endif; ?>><?php echo $value['label'] ?></option>
                            <?php endforeach; ?>
                        </select>
                    </td>
                </tr>
            <tr>
                <td class="label"><strong><label for="is_arpayments_allowed"><?php echo $this->__('AR Payment Allowed') ?></label></td>
                <td>
                    <select name="is_arpayments_allowed" id="is_arpayments_allowed">
                        <?php foreach ($arpaymentOptions as $key => $value): ?>
                            <option value="<?php echo $value['value'] ?>" <?php if ($erpCustomer->getIsArpaymentsAllowed() == $value['value']) : ?>selected="selected"<?php endif; ?>><?php echo $value['label'] ?></option>
                        <?php endforeach; ?>
                    </select>
                </td>
            </tr>                
        </table>
        <?php echo $this->getChildHtml('erp-left-box-information') ?>
    </fieldset>
        <?php echo $this->getChildHtml('erp-left-box') ?>
</div>
<div class="grid_display">
<?php echo $this->getChildHtml();?>
</div>    

<style>
    .erp_infomation td {
        padding:5px 15px 5px 5px;
    }
    .erp_infomation td.label {
        width: 200px;
    }
    .grid_display{clear:both;}
</style>