<?php
/**
 * WARNING: IF YOU MAKE ECC SPECIFIC CHANGES TO THIS FILE, THEY MUST ALSO BE ADDED TO THE RWD FILE TOO
 * rwd/default/template/customerconnect/cart/product/csvupload_quickorderpad.phtml
 */
/**
 * Edit cart/csvupdate template
 *
 * @see Epicor_Comm_Block_Cart_Product_Csvupdate
 */
?>
<form id="product_csv_import_form" action="<?php echo $this->getUrl('customerconnect/rfqs/importProductCsv') ?>" 
      method="post" enctype="multipart/form-data">
    <div class="fieldset">
        <h2 class="legend"><?php echo $this->__('Add to Quote by CSV'); ?></h2>
        <ul class="form-list">
            <li>
                <label for="q"><?php echo $this->__('Click browse to select file'); ?></label>
                <div class="input-box">
                    <input id="input-file" type="file" name="import_product_csv_file" class="input-file required-entry"/>
                </div>
            </li>
            <li>
                <input type="submit" value="<?php echo $this->__('Upload'); ?>" />
            </li>
        </ul>
    </div>
</form>