<div class="page-title">
   <h1><?php echo Mage::helper('sales')->__('Returns') ?></h1>
</div>
<form action="<?php echo $this->getActionUrl() ?>" id="oar_widget_orders_and_returns_form" method="post" name="guest_post">
    <div class="fieldset">
        <h2 class="legend"><?php echo Mage::helper('sales')->__('Order Information') ?></h2>
        <ul class="form-list">
            <li>
                <div class="field">
                    <label for="oar_order_id" class="required"><em>*</em><?php echo Mage::helper('sales')->__('Order ID') ?></label>
                    <div class="input-box">
                        <input name="oar_order_id" id="oar_order_id" title="<?php echo Mage::helper('sales')->__('Order ID') ?>" value="" class="input-text required-entry" type="text" />
                    </div>
                </div>
            </li>
            <li class="wide">
                <p>
                    <?php echo Mage::helper('sales')->__('Enter the billing last name and email/ZIP as in the order billing address') ?>.
                </p>
                <div class="field">
                    <label for="oar_billing_lastname" class="required"><em>*</em><?php echo Mage::helper('sales')->__('Billing Last Name') ?></label>
                    <div class="input-box">
                        <input name="oar_billing_lastname" id="oar_billing_lastname" title="<?php echo Mage::helper('sales')->__('Billing Last Name') ?>" value="" class="input-text required-entry" type="text" />
                    </div>
                </div>
            </li>
            <li class="fields">
                <div class="field">
                    <label for="quick_search_type_id"><?php echo Mage::helper('sales')->__('Find Order By:') ?></label>
                    <div class="input-box">
                       <select name="oar_type" id="quick_search_type_id" class="select guest-select" title="" onchange="showIdentifyBlock(this.value);">
                           <option value="email">Email Address</option>
                           <option value="zip">ZIP Code</option>
                       </select>
                    </div>
                </div>
                <div class="field" id="oar-email" style="display:none;">
                    <label for="oar_email" class="required"><em>*</em><?php echo Mage::helper('sales')->__('Email Address') ?></label>
                    <div class="input-box">
                        <input name="oar_email" id="oar_email" title="<?php echo Mage::helper('sales')->__('Email Address') ?>" value="" class="input-text validate-email required-entry" type="text" />
                    </div>
                </div>
                <div class="field" id="oar-zip" style="display:none;">
                    <label for="oar_zip" class="required"><em>*</em><?php echo Mage::helper('sales')->__('Billing ZIP Code') ?></label>
                    <div class="input-box">
                        <input name="oar_zip" id="oar_zip" title="<?php echo Mage::helper('sales')->__('Billing ZIP Code') ?>" value="" class="input-text required-entry" type="text" />
                    </div>
                </div>
            </li>
        </ul>
    </div>
    <div class="buttons-set">
        <p class="required"><?php echo Mage::helper('sales')->__('* Required Fields') ?></p>
        <input type="text" name="hideit" id="hideit" value="" style="display:none !important;" />
        <button type="submit" title="<?php echo Mage::helper('sales')->__('Continue') ?>" class="button"><span><span><?php echo Mage::helper('sales')->__('Continue') ?></span></span></button>
    </div>
</form>
<script type="text/javascript">
//<![CDATA[
    if ($('quick_search_type_id').value == 'zip') {
        $('oar-zip').show();
        $('oar-email').hide();
    } else {
       $('oar-zip').hide();
       $('oar-email').show();
    }

   var dataForm = new VarienForm('oar_widget_orders_and_returns_form', true);

   function showIdentifyBlock(id)
   {
       if (id == 'zip') {
           $('oar-zip').show();
           $('oar-email').hide();
       } else if (id == 'email') {
           $('oar-zip').hide();
           $('oar-email').show();
       }
       return false;
   }
//]]>
</script>
