<?php
/* @var $this Epicor_SalesRep_Block_Account_Dashboard_ErpSelector */
if (Mage::getStoreConfigFlag('epicor_salesrep/general/masquerade_search_dashboard')) {
    return;
}
$erpAccounts = $this->getErpAccounts(true);
?><div class="box-info box-account col-1">
    <div class="box-head">
        <h2><?php echo $this->getTitle(); ?></h2>
    </div>
    <form action="<?php echo $this->getActionUrl(); ?>" method="post" id="masquerade-as">
        <input type="hidden" name="return_url" value="<?php echo $this->getReturnUrl(); ?>" />
        <ul class="form-list">
            <li>
                <label for="masquerade_as" class="required"><em>*</em><?php echo $this->__('Masquerade as'); ?></label>
                <div class="input-box masquerade_search_options_box">
                    <select name="masquerade_as" id="masquerade_as" class="required-entry validate-select" title="<?php echo $this->__('Masquerade as'); ?>">
                        <option><?php echo $this->__('Select an ERP Account'); ?></option>
                        <?php foreach ($erpAccounts as $erp_account): ?>
                            <option <?php if ($this->isMasqueradeAccount($erp_account)): ?>selected="selected" <?php endif; ?>value="<?php echo $erp_account->getEntityId(); ?>"><?php echo $erp_account->getName(); ?></option>
                        <?php endforeach; ?>
                    </select>
                </div>
                <div>
                    <?php if ($this->displaySearchButton()) : ?>
                        <button id="masquerade_search" type="button" title="<?php echo $this->__('Search') ?>" class="button" ><span><span><?php echo $this->__('Search') ?></span></span></button>
                    <?php endif; ?>
                </div>
            </li>   

        </ul>
        <div class="actions salesrep_masq_button">
            <?php if (!$this->isMasquerading()): ?>
                <button type="submit" title="<?php echo $this->__('Begin Masquerade'); ?>" class="button"><span><span><?php echo $this->__('Begin Masquerade'); ?></span></span></button>
            <?php else: ?>
                <button type="submit" title="<?php echo $this->__('Switch Account'); ?>" class="button"><span><span><?php echo $this->__('Switch Account'); ?></span></span></button>
            <?php endif; ?>
        </div>
    </form>
    <?php if ($this->isMasquerading()): ?>
        <form action="<?php echo $this->getActionUrl(); ?>" method="post" id="masquerade-as">
            <input type="hidden" name="return_url" value="<?php echo $this->getReturnUrl(); ?>" />
            <div class="actions" id ="masquerade_end">
                <button  type="submit" title="<?php echo $this->__('End Masquerade'); ?>" class="button"><span><span><?php echo $this->__('End Masquerade'); ?></span></span></button>
            </div>
        </form>
    <?php endif; ?>
</div>

<script type="text/javascript">
    //< ![CDATA[
    var masqueradeAsForm = new VarienForm('masquerade-as');
    //]]> 
    if ($("masquerade_search")) {
        $("masquerade_search").observe('click', function () {
            var overlay_margin = parseFloat(($('window-overlay').getWidth() * .40) / 2);
            $('window-overlay').insert('<iframe id="search_iframe" width="60%" top="20%" src="" frameborder="0" onload="resizeIframe(this)" style="display:none"></iframe>');
            $$('iframe').first().setStyle({left: overlay_margin + 'px'});
            $('search_iframe').src = '/salesrep/account/masqueradepopup';
            $('search_iframe').show();
            $('window-overlay').show();
        }
        );
    }

    function resizeIframe(obj) {
        obj.style.height = parseInt(obj.contentWindow.document.body.scrollHeight + 50) + 'px';
    }

</script>