<?php
/* @var $this Epicor_Comm_Block_Catalog_Product_View_Options_Type_Ecc_Text */
?>
<?php $_option = $this->getOption(); ?>
<dt><label<?php if ($_option->getIsRequire()) echo ' class="required"' ?>><?php if ($_option->getIsRequire()) echo '<em>*</em>' ?><?php echo $this->escapeHtml($_option->getTitle()) ?></label>
<?php echo $this->getFormatedPrice() ?></dt>
<dd<?php if ($_option->decoratedIsLast) { ?> class="last"<?php } ?>>
    <div class="input-box">
        <?php if ($_option->getType() == Epicor_Comm_Model_Catalog_Product_Option::OPTION_TYPE_ECC_TEXT): ?>
            <input type="text" onchange="opConfig.reloadPrice()" id="options_<?php echo $_option->getId() ?>_text" class="input-text<?php echo $_option->getIsRequire() ? ' required-entry' : '' ?> <?php echo $_option->getMaxCharacters() ? ' validate-length maximum-length-' . $_option->getMaxCharacters() : '' ?> product-custom-option <?php echo $this->getValidationClass($_option); ?>" name="options[<?php echo $_option->getId() ?>]" value="<?php echo $this->escapeHtml($_option->getEpicorDefaultValue()) ?>" />
            <?php if ($this->getValidationClass($_option) == 'validate-csns'): ?>
                <input type="hidden" value="validate" id="options_<?php echo $_option->getId() ?>_text_mode"/>
                <input type="hidden" value="<?php echo Mage::getUrl('comm/message/csns'); ?>" id="options_<?php echo $_option->getId() ?>_text_csnsurl"/>
                <input type="hidden" value="<?php echo $this->getProduct()->getSku(); ?>" id="options_<?php echo $_option->getId() ?>_text_sku"/>
            <?php endif; ?>
        <?php endif; ?>
        <?php if ($_option->getMaxCharacters()): ?>
            <p class="note"><?php echo Mage::helper('catalog')->__('Maximum number of characters:') ?> <strong><?php echo $_option->getMaxCharacters() ?></strong></p>
        <?php endif; ?>
    </div>
</dd>
