
<div class="entry-edit box-right">
    <div class="entry-edit-head">
        <h4 class="icon-head head-account">
            <?php echo $this->__('Customer Information'); ?>
        </h4>
    </div>
    <div class="fieldset">
        <table cellspacing="0" class="form-list">
            <tr>
                <td class="label"><label><?php echo $this->__('Name'); ?></label></td>
                <td class="value"><strong><?php echo $this->getCustomer()->getName(); ?></strong></td>
            </tr>
            <tr>
                <td class="label"><label><?php echo $this->__('Email'); ?></label></td>
                <td class="value"><strong><?php echo $this->getCustomer()->getEmail(); ?></strong></td>
            </tr>
            <tr>
                <td class="label"><label><?php echo $this->__('Erp Account'); ?></label></td>
                <td class="value"><strong><?php echo $this->getCustomerGroup()->getName(); ?></strong></td>
            </tr>
            <?php if($this->getCustomerGroup()->getErpCode()) :?>
            <tr>
                <td class="label"><label><?php echo $this->__('Company'); ?></label></td>
                <td class="value"><strong><?php echo $this->getCustomerGroup()->getCompany(); ?></strong></td>
            </tr>
            <tr>
                <td class="label"><label><?php echo $this->__('Short code'); ?></label></td>
                <td class="value"><strong><?php echo $this->getCustomerGroup()->getShortCode(); ?></strong></td>
            </tr>
            <?php endif; ?>
        </table>
    </div>
</div>