<div id="grouped_update_cart">  
    <?php $buttonTitle = $this->__('Update Cart'); ?>
    <?php $itemId = $this->getRequest()->getParam('itemid');?>   
     <input type="hidden" name="cart_item_id" value="<?php echo $itemId ?>" title="Update Config Value" />
     <input type="hidden" name="update_config_value" value="true" title="Update Config Value" />
    <div class="add-to-cart">
        <button type="button" title="<?php echo $buttonTitle ?>" class="button btn-cart" onclick="productAddToCartForm.submit(this)"><span><?php echo $buttonTitle ?></span></button> 
        <?php echo $this->getChildHtml('', true, true) ?>
    </div>
</div>
