<?php
/**
 * Sales Rep Sub Menu
 * 
 * @category   Epicor
 * @package    Epicor_SalesRep
 * @author     Epicor Websales Team
 */

/* @var $this Epicor_SalesRep_Block_Account_Manage_Menu */
$first = true;
?>
<div id="sales_rep_menu">
    <?php foreach ($this->getMenuItems() as $link => $label) : ?>
        <?php if (!$first) : ?>&nbsp;|&nbsp;<?php endif; ?>
        <?php if ($this->isCurrentPage($link)) : ?>
            <span class="salesrep-link-selected"><?php echo $this->__($label); ?></span>
        <?php else: ?>
            <a class="salesrep-link" href="<?php echo $this->getLink($link); ?>"><?php echo $this->__($label); ?></a>
        <?php endif; ?>
        <?php $first = false; ?>
    <?php endforeach; ?>
</div>