<?php
/**
 * 
 */
/* @var $this Epicor_SalesRep_Block_Account_Manage_Pricingrules */
?>
<script type="text/javascript">
    var BLANK_URL = '<?php echo $this->getJsUrl(); ?>blank.html';
    var BLANK_IMG = '<?php echo $this->getJsUrl(); ?>spacer.gif';
    var BASE_URL = '<?php echo $this->getUrl('*'); ?>';
    var SKIN_URL = '<?php echo $this->getSkinUrl(); ?>';
    var FORM_KEY = '<?php echo $this->getFormKey(); ?>';
    Ext.BLANK_IMAGE_URL = BLANK_IMG;
    Ext.UpdateManager.defaults.loadScripts = false;
    Ext.UpdateManager.defaults.disableCaching = true;
</script>
<?php echo $this->getChildHtml('manage.pricingrulesform', false); ?>
<script type="text/javascript">
    pricingRules = new Epicor_SalesRep_Pricing.pricingRules('pricing_rule_form', 'pricing_rules_table', 'pricing_rules');
</script>
<?php
echo $this->getChildHtml('manage.pricingrules', false);
