<?php
$helper = Mage::helper('epicor_salesrep/account_manage');
/* @var $helper Epicor_SalesRep_Helper_Account_Manage */

if ($helper->isManagingChild()):
    ?>
    <h1><?php echo $this->__('Managing Sales Rep Account: '), $helper->getManagedSalesRepAccount()->getName(); ?></h1>
    <p><a class="salesrep-link" href="<?php echo Mage::getUrl('*/*/reset'); ?>"><?php echo $this->__('Return to My Sales Rep Account'); ?></a></p>
<?php else: ?>
    <h1><?php echo $this->__('My Sales Rep Account'); ?></h1>
<?php endif;