<div class="box-info box-account <?php echo $this->getOnRight() ? 'col-2 ' : 'col-full'; ?>">
    <div class="box-head">
        <h2><?php echo $this->getTitle(); ?></h2>
    </div>
    <ul class="info-list col-count-<?php echo $this->getColumnCount(); ?>">
        <?php foreach ($this->_infoData as $label => $value): ?>
            <li >
                <?php if(preg_match("~\bFOB\b~",$label)): ?>
                    <span class="label">Incoterms &reg; 2010 :</span>
                <?php else: ?>
                    <span class="label"><?php echo $label; ?></span>
                <?php endif; ?>
                <span class="value"><?php echo $value; ?></span>
            </li>
        <?php endforeach; ?>
    </ul>
</div>