<?php
$_product = Mage::registry('current_product');
$loopProduct = Mage::registry('current_loop_product') ? : $_product;
/* @var $loopProduct Epicor_Comm_Model_Product */
$productLocation = Mage::registry('current_location') ? : $_product;

$helper = $this->helper('epicor_comm');
/* @var $helper Epicor_Comm_Helper_Data */
$_productHelper = $this->helper('epicor_comm/product');
/* @var $_productHelper Epicor_Comm_Helper_Product */

//locations stuff
$locHelper = $this->helper('epicor_comm/locations');
/* @var $helper Epicor_Comm_Helper_Locations */
$showLocations = $locHelper->isLocationsEnabled();

if ($showLocations && !Mage::registry('current_location')) : 
    $showAddToCart = false;
else:
    $showAddToCart = $helper->isFunctionalityDisabledForCustomer('cart') ? false : true;
endif;

$showUom = Mage::getStoreConfigFlag('Epicor_Comm/units_of_measure/display_in_cart');
$showInColumn = Mage::getStoreConfigFlag('Epicor_Comm/units_of_measure/display_in_cart_column');
?>
<?php if ($showAddToCart) : ?>

    <td class="action last">
        <?php echo $this->getChildHtml('epicor_extra', false); ?>
        <?php if ($loopProduct->isSaleable()): ?>
            <?php if ($_product->getConfigurator() && !$this->getHideConfigurator()): ?>
                <?php if ($this->getParentBlock()->getLicensed()): ?>
                    <?php echo $this->getParentBlock()->getChildHtml('configurableaddtocartlist', false); ?>
                <?php endif; ?>
            <?php elseif (($_product->getTypeId() == 'configurable' || $this->productHasOptions($_product, true)) && !$this->getHideConfigurator()): ?>
                <div class="configurable_addtocart">  
                    <?php $buttonTitle = $this->__('Configure Product'); ?>
                    <div class="add-to-cart">
                        <a href="<?php echo $_productHelper->getProductUrl($_product, array('returnurl' => base64_encode(Mage::helper('core/url')->getCurrentUrl())), true); ?>">
                            <button type="button" title="<?php echo $buttonTitle ?>" class="button btn-cart" onclick="">
                                <span><span>
                                        <?php echo $buttonTitle ?>
                                    </span></span>
                            </button>
                        </a>
                    </div>
                </div>
            <?php else : ?>
                <?php $qtyName = $this->getQtyFieldName($_product, $loopProduct, $productLocation); ?>
                    <?php $addHiddenLoc = $this->addHiddenLocationCode($_product); ?>

                    <?php
                    if (($_product->getTypeId() != 'grouped') || ($loopProduct->getPackSize() != '' && $_product->getStkType() == 'grouped')) {
                        $uomdis = $this->__($this->htmlEscape($loopProduct->getPackSize() ?: $_product->getDefaultUom()));
                    } else {
                        $uomdis = $this->__($this->htmlEscape($loopProduct->getName()));
                    }

                    $uomDisp = strtolower(str_replace(' ', '_', $uomdis));
                    $locationDisp = strtolower(preg_replace("/[^a-zA-Z]+/", "", ($productLocation) ? $productLocation->getName() : ''));
                    $dynamicId = 'qty_' . $uomDisp . '_' . $locationDisp . '_' . $_product->getId();
                    ?>

        <form method="post" action="<?php echo $this->getAddToCartUrl($_product); ?>" class="addtobasketform" id="<?php echo $dynamicId; ?>">
                        <input type="hidden" value="<?php echo $this->getReturnUrl(); ?>" name ="return_url"/>                    
                    <input type="hidden" value="<?php echo $_product->getId(); ?>" name="product">
                    <?php if ($addHiddenLoc): ?>
                        <?php
                        $locationCode = $_product->getRequiredLocation();
                        $branchHelper = Mage::helper('epicor_branchpickup');
                        $branchSelected = $branchHelper->getSelectedBranch();
                        if ($branchSelected) {
                            $locationCode = $branchSelected;
                        }
                        ?>
                        <input type="hidden" value="<?php echo $locationCode; ?>" name="location_code"/>
                    <?php endif; ?>
                        <label for="qty_<?php echo $_product->getId(); ?>"></label>
                                    <?php
                                    $commHelper = Mage::helper('epicor_comm');
                                    $decimalPlaces = $commHelper->getDecimalPlaces(Mage::getResourceModel('catalog/product')->getAttributeRawValue($loopProduct->getId(), 'decimal_places', Mage::app()->getStore()->getStoreId()));
            ?>
                                                <input decimal ="<?php echo $decimalPlaces; ?>" id="qty_<?php echo $_product->getId(); ?>" type="text" name="<?php echo $qtyName; ?>" maxlength="12" value="<?php echo $this->getProductDefaultQty() * 1 ?>" title="<?php echo $this->__('Qty') ?>" class="input-text qty addall_qty" />
                                    <?php if ($loopProduct->getTypeId() == 'bundle'): ?>
                        <?php $selectionCollection = $loopProduct->getTypeInstance(true)->getSelectionsCollection($loopProduct->getTypeInstance(true)->getOptionsIds($loopProduct), $loopProduct); ?>
                        <?php foreach ($selectionCollection as $option) : ?>
                            <input type="hidden" name="bundle_option[<?php echo $option->option_id; ?>]" value="<?php echo $option->selection_id; ?>" />
                        <?php endforeach; ?>
                    <?php endif; ?>
                                        <button onclick="preventFormSubmit('qop-list', '<?php echo $dynamicId; ?>',true);" type="sumbit" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-qop" ><span><?php echo $this->__('>>') ?></span></button>
                                </form>
                <?php if ($this->productHasOptions($_product) && !$this->getHideConfigurator()): ?>
                    <div class="configurable_addtocart">  
                        <?php $buttonTitle = $this->__('Configure Product'); ?>
                        <div class="add-to-cart">
                            <a href="<?php echo $_productHelper->getProductUrl($_product, array('returnurl' => base64_encode(Mage::helper('core/url')->getCurrentUrl()))); ?>">
                                <button type="button" title="<?php echo $buttonTitle ?>" class="button btn-cart" onclick="">
                                    <span><span>
                                            <?php echo $buttonTitle ?>
                                        </span></span>
                                </button>
                            </a>
                        </div>
                    </div>
                <?php endif; ?>
                <?php if ($showUom && !$showInColumn) : ?>
                    <span class="nobr" style="display:block;">
                        <?php if (($_product->getTypeId() != 'grouped') || ($loopProduct->getPackSize() != '' && $_product->getStkType() == 'grouped')) : ?>                
                            <?php $uom = $this->__($this->htmlEscape($loopProduct->getPackSize() ? : $_product->getDefaultUom())) ?>
                        <?php else: ?>
                            <?php $uom = $this->__($this->htmlEscape($loopProduct->getName())) ?>
                        <?php endif ?> 
                        <?php if (!empty($uom)) : ?>
                            <?php echo ' x ' . $uom; ?>
                        <?php endif ?> 
                    </span>
                <?php endif; ?>
            <?php endif; ?>
        <?php else: ?>
            <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock'); ?></span></p>

        <?php endif; ?>
<?php else: ?>
     <td class="action last">
<?php endif; ?>
    </td>