<?php
$_product = Mage::registry('current_product');

$rowspan = Mage::registry('current_rowspan');
$showProductImage = $this->showProductImageDisplay();
?>
<?php if ($showProductImage) : ?>
    <td class="image" <?php if ($rowspan) : ?>rowspan="<?php echo $rowspan ?><?php endif; ?>">
        <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'thumbnail'), null, true) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'thumbnail')->resize(50); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'thumbnail'), null, true) ?>" /></a>
    </td>
<?php endif; ?>