<?php
$_product = Mage::registry('current_product');

$rowspan = Mage::registry('current_rowspan');
$_helper = $this->helper('catalog/output');
?>
<td class="productname" <?php if ($rowspan) : ?>rowspan="<?php echo $rowspan ?>"<?php endif; ?>>
<?php $_productNameStripped = $this->stripTags($_product->getName(), null, true); ?>
    <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped; ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?></a></h2>
<div class="desc std skus">
    <ul>
<?php
$sku_iterator = 0;
foreach ($_product->getSkus() as $sku):
    ?>
            <li><?php echo $sku; ?></li>
            <?php
            $sku_iterator++;
        endforeach;
        ?>
    </ul>
</div>
</td>