<?php
$locHelper = $this->helper('epicor_comm/locations');
/* @var $helper Epicor_Comm_Helper_Locations */
$showLocations = $locHelper->isLocationsEnabled();
$allSourceLocations = (Mage::getStoreConfig('epicor_comm_locations/global/stockvisibility') == 'all_source_locations') ? true : false;
?>
<?php if ($showLocations && !$allSourceLocations) : ?>
    <div class="qop-sort">
        <label><?php echo $this->__('Organise First By '); ?></label>
        <select onchange="setLocation(this.value)">
            <option <?php if($this->getCurrentSortBy() == 'uom'): ?> selected="selected"<?php endif ?> value="<?php echo $this->getSortByUrl('uom');?>"><?php echo $this->__('Unit of Measure');?></option>
            <option <?php if($this->getCurrentSortBy() == 'location'): ?> selected="selected"<?php endif ?> value="<?php echo $this->getSortByUrl('location');?>"><?php echo $this->__('Location');?></option>
        </select>
    </div>
<?php endif; ?>

<?php
echo $this->getOrigPager();
?>