<?php
/* @var $this Epicor_Customerconnect_Block_Customer_Returns_Details_Statusinfo */

$rmaStatus = $this->getReturnMapping();

if ($rmaStatus->getStatusText()) :
    ?>
    <div class="box-info box-account <?php echo $this->getOnRight() ? 'col-2 ' : 'col-full'; ?>">
        <div class="box-head">
            <h2><?php echo $this->getTitle(); ?></h2>
        </div>
        <div class="info-list col-count-1">
            <?php echo $rmaStatus->getStatusText(); ?>
        </div>
    </div>
    <?php

endif;