<?php
/* @var $this Epicor_Comm_Block_Checkout_Cart_Item_Comment */
?>
<div class="linecomment">
    <?php if ($this->isCommentAllowed()) : ?>
        <fieldset class="field_comment">
            <label for="line_comment_<?php echo $this->getItem()->getId() ?>"><?php echo Mage::helper('epicor_comm')->__('Line Comment') ?></label>
            <div class="input-box">
                <textarea name="cart[<?php echo $this->getItem()->getId() ?>][ecc_line_comment]" class="line_comment" id="line_comment_<?php echo $this->getItem()->getId() ?>"><?php echo $this->getItem()->getEccLineComment() ?></textarea>
            </div>
        </fieldset>
        <?php if ($this->getCommentLimit() > 0): ?>
            <script>
                jQuery(function () {
                    jQuery('#line_comment_<?php echo $this->getItem()->getId() ?>').maxlength({
                        maxCharacters: <?php echo $this->getCommentLimit(); ?>, // Characters limit
                        statusClass: "max-len-feedback", // The class on the status div
                        statusText: "<?php echo Mage::helper('epicor_comm')->__('Chars Remaining'); ?>", // The status text
                    });
                })
            </script>
        <?php endif; ?>
    <?php endif; ?>
</div>