<?php
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
$_log = $this->getLog();
?>
<style>
    .xmlmsg{
        width:50%;
        display:inline-block;
/*        
        margin-left:5px;
        margin-right:5px;
*/
        overflow:auto;
        float:left;
    }    
    
    .xmlmsg pre {
        width:200px;
    }
</style>
<div class="entry-edit" style="clear:left;">
    <div class="entry-edit-head">
        <h4>Message XML</h4>
    </div>
    <fieldset id="order_erp_status_form">
        <div class="xmlmsg">
            <h4><?php echo Mage::helper('adminhtml')->__('Xml Request') ?></h4>
            <pre><?php echo $this->getFirstXml();?></pre>
        </div>
        <div class="xmlmsg">
            <h4><?php echo Mage::helper('adminhtml')->__('Xml Response') ?></h4>
            <pre><?php echo $this->getSecondXml(); ?></pre>
        </div>
    </fieldset>
</div>
