<?php
/* @var $this Epicor_Comm_Block_Customer_Returns_Attachments */
?>
<script type="text/javascript">
//<![CDATA[
    document.observe('dom:loaded', function (element) {
        attachments = new Attachments('attachments-return-form');
    });
//]]>
</script>
<?php echo $this->getReturnBarHtml(); ?>
<div>
    <form id="attachments-return-form" target="attachment-form-iframe" action="<?php echo $this->getUrl('epicor_comm/returns/saveAttachments') ?>" method="post" enctype="multipart/form-data">
        <fieldset>
            <input type="hidden" name="return_id" value="<?php echo $this->getEncodedReturn(); ?>" />
            <?php $this->getChild('formkey'); ?>
            <?php echo $this->getAttachmentsHtml(); ?>
        </fieldset>
        <div id="attachments-buttons-container" class="buttons-set">
            <button class="button" title="<?php echo $this->__('Continue'); ?>" type="submit" id="attachments-submit"><span><span><?php echo $this->__('Continue'); ?></span></span></button>
            <span style="display:none;" id="attachments-please-wait" class="please-wait">
                <img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" alt="<?php echo $this->__('Please wait...') ?>" title="<?php echo $this->__('Please wait...') ?>" class="v-middle" /> <?php echo $this->__('Please wait...') ?>
            </span>
        </div>
    </form>
</div>
