<?php
/**
 * Locations template
 *
 */
/* @var $this Epicor_Comm_Block_Catalog_Product_View_Type_Grouped_Locations */
$_product = $this->getProduct();
/* @var $_product Epicor_Comm_Model_Product */

$editItem = $this->getRequest()->getParam('itemId');
$editQty = $this->getRequest()->getParam('qty');

$branchpickupHelper = Mage::helper('epicor_branchpickup');
/* @var $branchpickupHelper Epicor_BranchPickup_Helper_Data */

$helper = $this->helper('epicor_comm');
/* @var $helper Epicor_Comm_Helper_Data */

$locations = $this->allChildrenLocationCodes($_product);
$hasLocations = count($locations) > 0;

$showPrices = $helper->isFunctionalityDisabledForCustomer('prices') ? false : true;
$showQty = $helper->isFunctionalityDisabledForCustomer('cart') ? false : true;
$showPrices = $this->getHidePrices() ? false : $showPrices;

$uomBeforeLoc = $this->getPrimarySort() == 'uom' ? true : false;

$locHelper = $this->helper('epicor_comm/locations');
/* @var $helper Epicor_Comm_Helper_Locations */

echo $this->getChildHtml('product_type_data_extra');
$allSourceLocations = (Mage::getStoreConfig('epicor_comm_locations/global/stockvisibility') == 'all_source_locations') ? true : false;
$singleLocation = (count($locations) == 1) ? true : false;
$col1Header = $uomBeforeLoc ? $this->__('Product Name') : $this->__('Location');
$col2Header = (!$singleLocation && $uomBeforeLoc) ? $this->__('Location') : $this->__('Product Name');
if ($hasLocations ) :
    ?>
    <table class="data-table grouped-items-table" id="super-product-table">
          <?php if(!$singleLocation): ?>
                <col />
           <?php endif; ?>      
        <col />
        <?php if ($showPrices && $this->getCanShowProductPrice($_product)): ?>
            <col />
        <?php endif; ?>
        <?php if ($showQty && $_product->isSaleable()): ?>
            <col width="1" />
        <?php endif; ?>
        <thead>
            <tr>
                <?php if(!$singleLocation): ?>
                    <th><?php echo $col1Header; ?></th>
                <?php endif; ?>
                    <th><?php echo $col2Header ?></th>
                <?php if ($showPrices && $this->getCanShowProductPrice($_product)): ?>
                    <th class="a-right"><?php echo $this->__('Price') ?></th>
                <?php endif; ?>
                <?php if ($showQty && $_product->isSaleable()): ?>
                    <th class="a-center"><?php echo $this->__('Qty') ?></th>
                <?php endif; ?>
            </tr>
        </thead>
        <tbody>
            <?php $primary = $this->getPrimaryItems($_product); ?>
            <?php foreach ($primary as $prime): ?>
                <?php $secondary = $this->getSecondaryItems($_product, $prime); ?>
                <?php $primaryDisplayed = false; ?>
                <?php $primaryRowSpan = count($secondary); ?>
                <?php foreach ($secondary as $second): ?>
                    <?php $location = $uomBeforeLoc ? $second : $prime; /* @var $location Epicor_Comm_Model_Location_Product */ ?>
                    <?php $childProduct = $uomBeforeLoc ? $prime : $second; /* @var $childProduct Epicor_Comm_Model_Product */ ?>
                    <?php $childProduct->setToLocationPrices($location->getLocationCode()); ?>
                    <?php unset($second); ?>
                    <?php
                    $commHelper = Mage::helper('epicor_comm');
                    $uom = ($childProduct->getPackSize() != '' && $_product->getStkType() == 'grouped') ? $childProduct->getPackSize() : $childProduct->getName();
            $col1Content = $uomBeforeLoc ? $uom : $location->getName();
            $col2Content = (!$singleLocation && $uomBeforeLoc) ? $location->getName() : $uom;
                    ?>
                    <tr>   
                        <?php if(!$singleLocation): ?>
                            <?php if (!$primaryDisplayed) : ?>
                                <td rowspan="<?php echo $primaryRowSpan; ?>"><?php echo $this->__($this->htmlEscape($col1Content)); ?></td>
                                <?php $primaryDisplayed = true; ?>
                            <?php endif; ?>
                        <?php endif; ?>
                        <td>
                            <?php echo $this->__($this->htmlEscape($col2Content)); ?>
                            <?php if ($childProduct->isSaleable()) : ?>   
                                            <?php
                                            $decimalPlaces = $commHelper->getDecimalPlacesView(Mage::getResourceModel('catalog/product')->getAttributeRawValue($childProduct->getId(), 'decimal_places', Mage::app()->getStore()->getStoreId()));
                                            switch ($childProduct->getStockType()):
                                    case 'bool':
                                        ?>
                                        <?php if ($childProduct->isAvailable()): ?>
                                            <p class="availability in-stock"><span><?php echo $this->__('In stock') ?></span></p>
                                        <?php else: ?>
                                            <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                                        <?php endif; ?>
                                        <?php break; ?> 
                                    <?php case 'range': ?>
                                        <?php $_img = $childProduct->getStockRange(); ?>
                                        <img src="<?php echo $_img['src'] ?>" alt="<?php echo $_img['alt'] ?>" title="<?php echo $_img['title'] ?>" />        
                                        <?php break; ?> 
                                    <?php case 'level': ?>
                                        <?php if($branchpickupHelper->getSelectedBranch()): ?>
                                            <?php $aggregateStock = $branchpickupHelper->getStockForAllLoc($childProduct); ?>
                                            <?php $_showInventory = $branchpickupHelper->canShowInventory($childProduct); ?>
                                        <?php else: ?>
                                        <?php $_showInventory = $location->getShowInventory(); ?>
                                            <?php $aggregateStock = $childProduct->getStockLevel(); ?>
                                        <?php endif; ?>
                                        <?php if($_showInventory): ?>
                                            <p class="availability in-stock"><?php echo $this->__('Stock:') ?> <span><?php echo $commHelper->truncateZero($aggregateStock, $decimalPlaces); ?></span></p>
                                        <?php endif; ?>
                                    <?php break; ?>         
                                <?php endswitch; ?>  
                            <?php endif; ?> 
                            <?php $this->getChild('related_branch')->setData('current_uom', $childProduct); ?>
                            <?php echo $this->getChildHtml('related_branch', false); ?>
                        </td>
                        <?php if ($showPrices && $this->getCanShowProductPrice($_product)): ?>
                            <td class="a-right">
                                <?php if ($this->getCanShowProductPrice($childProduct)): ?>
                                
                                
                                    <?php echo $this->getPriceHtml($location, $childProduct, true); ?>
                                    <?php echo $this->getTierPriceHtml($location, $childProduct); ?>
                                <?php endif; ?>
                            </td>
                        <?php endif; ?>
                        <?php if ($showQty && $_product->isSaleable()): ?>
                            <td class="a-center">
                                                <?php if ($childProduct->isSaleable()) : ?>
                                                    <?php $decimalPlaces = $commHelper->getDecimalPlaces(Mage::getResourceModel('catalog/product')->getAttributeRawValue($childProduct->getId(), 'decimal_places', Mage::app()->getStore()->getStoreId())); ?>
                                                    <input decimal="<?php echo $decimalPlaces; ?>" type="text" name="super_group_locations[<?php echo $location->getLocationCode() ?>][<?php echo $childProduct->getId() ?>]" maxlength="12" value="<?php echo $editQty ?>" title="<?php echo $this->__('Qty') ?>" class="input-text qty" />
                                                    <?php if ($childProduct->getTypeId() == 'bundle'): ?>
                                        <?php $selectionCollection = $childProduct->getTypeInstance(true)->getSelectionsCollection($childProduct->getTypeInstance(true)->getOptionsIds($childProduct), $childProduct); ?>
                                        <?php foreach ($selectionCollection as $option) : ?>
                                            <input type="hidden" name="bundle_option[<?php echo $option->option_id; ?>]" value="<?php echo $option->selection_id; ?>" />
                                        <?php endforeach; ?>
                                    <?php endif; ?>
                                <?php else: ?>
                                    <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                                </td>
                            <?php endif; ?>
                        <?php endif; ?>
                    </tr>
                <?php endforeach; ?>
                <?php unset($prime); ?>
            <?php endforeach; ?>
        </tbody>
    </table>
    <script type="text/javascript">decorateTable('super-product-table')</script>
<?php endif; ?>
