<script type="text/javascript">
    Translator.add('One or more options is incorrect, please see page for details', '<?php echo $this->__('One or more options is incorrect, please see page for details'); ?>');
    Translator.add('You must supply at least one Contact', '<?php echo $this->__('You must supply at least one Contact'); ?>');
    Translator.add('You must supply at least one Line', '<?php echo $this->__('You must supply at least one Line'); ?>');
    Translator.add('One or more lines require configuration, please see lines with a "Configure" link', '<?php echo $this->__('One or more lines require configuration, please see lines with a "Configure" link'); ?>');
    Translator.add('You must provide an SKU for all non-custom parts', '<?php echo $this->__('You must provide an SKU for all non-custom parts'); ?>');
    Translator.add('You must provide a name for all custom parts', '<?php echo $this->__('You must provide a name for all custom parts'); ?>');
    Translator.add('All quantities must be valid', '<?php echo $this->__('All quantities must be valid'); ?>');
    Translator.add('SKU', '<?php echo $this->__('SKU'); ?>');
    Translator.add('Does not exist - select Custom Part', '<?php echo $this->__('Does not exist - select Custom Part'); ?>');
    Translator.add('Lines added successfully', '<?php echo $this->__('Lines added successfully'); ?>');
    Translator.add('One or more lines had errors:', '<?php echo $this->__('One or more lines had errors:'); ?>');
    Translator.add('One or more products require configuration. Please click on each "Configure" link in the lines list', '<?php echo $this->__('One or more products require configuration. Please click on each "Configure" link in the lines list'); ?>');
    Translator.add('Edit Configuration', '<?php echo $this->__('Edit Configuration'); ?>');
    Translator.add('No lines added', '<?php echo $this->__('No lines added'); ?>');
    Translator.add('Line(s) added successfully', '<?php echo $this->__('Line(s) added successfully'); ?>');
    Translator.add('One or more products require configuration. Please click on each "Configure" link in the lines list', '<?php echo $this->__('One or more products require configuration. Please click on each "Configure" link in the lines list'); ?>');
    Translator.add('Configure', '<?php echo $this->__('Configure'); ?>');
    Translator.add('TBA', '<?php echo $this->__('TBA'); ?>');
    Translator.add('Are you sure you want to delete?', '<?php echo $this->__('Are you sure you want to delete?'); ?>');
    Translator.add('That function is not available', '<?php echo $this->__('That function is not available'); ?>');
    Translator.add('Lines added successfully', '<?php echo $this->__('Lines added successfully'); ?>');
    Translator.add('Please enter a qty', '<?php echo $this->__('Please enter a qty'); ?>');
    Translator.add('Line added successfully', '<?php echo $this->__('Line added successfully'); ?>');
    Translator.add('One or more products require configuration. Please click on each "Configure" link in the lines list', '<?php echo $this->__('One or more products require configuration. Please click on each "Configure" link in the lines list'); ?>');
    Translator.add('Error occured in Ajax Call', '<?php echo $this->__('Error occured in Ajax Call'); ?>');
</script>