<?php

/* @var $this Epicor_Quickorderpad_Block_Form_Wrapper */
$csvUpload = Mage::getStoreConfigFlag('Epicor_Comm/basket_csv_upload/enabled_quickorderpad');

$listHelper = Mage::helper('epicor_lists/frontend');
/* @var $listHelper Epicor_Lists_Helper_Frontend */

?>
<div class="quickorderpad">
    <?php if (!$this->getHideTitle()) : ?>
    <div class="page-title">
        <h1><?php echo $this->getTitle() ?></h1>
    </div>
    <?php endif; ?>
    <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
    <div class="qop-search<?php if($csvUpload) : ?> csvincluded<?php endif; ?>">
        <?php echo $this->getChildHtml('search'); ?>
        <?php if($csvUpload) : ?>
            <?php echo $this->getChildHtml('csvupload'); ?>
        <?php endif; ?>
    </div>
    <div class="qop-productlist<?php if(Mage::getStoreConfigFlag('quickorderpad/general/show_cart_summary')) : ?> thinner<?php endif;?>" >
        <?php if(Mage::registry('search-query') != '' || $this->getRequest()->getParam('csv') || ($listHelper->listsEnabled() && $listHelper->getSessionList())) :
                echo $this->getChildHtml('search.result');
              else: ?>
                <div class="page-title">
                    <h1><?php echo $this->__('Enter a search Keyword / SKU') ?></h1>
                </div>
        <?php endif; ?>
    </div>
    <?php if(Mage::getStoreConfigFlag('quickorderpad/general/show_cart_summary')) : ?>
        <div class="qop-summary">
            <?php echo $this->getChildHtml('cart.sidebar'); ?>
        </div>
        <div class="qop-clear"></div>
    <?php endif; ?>
    <?php 
        echo $this->getChildHtml('basket');
        /*
        $showImages = Mage::getStoreConfigFlag('quickorderpad/general/show_quickorderpad_images');
        if($showImages){ 
        <script type="text/javascript" language="javascript">
            //jQuery(".image").show();
            $$('.qop-list .image').invoke(
                    'setStyle', {
                        display: 'table-cell'
            });
        </script>
        }
        */
    ?>
</div>