<?php
/**
 * Entity details page title
 * 
 * @category   Epicor
 * @package    Epicor_Customerconnect
 * @author     Epicor Websales Team
 */
/* @var $this Epicor_Customerconnect_Block_Customer_Title */
?>
<?php if ($this->canReorder()) : ?>
    <a href="<?php echo $this->getReorderUrl(); ?>" class="reorder link-reorder reorder-button"><?php echo $this->__('Reorder'); ?></a>
<?php endif; ?>
<?php if ($this->canReturn()) : ?>
    <a href="<?php echo $this->getReturnUrl(); ?>" class="return link-reorder"><?php echo $this->__('Return'); ?></a>
<?php endif; ?>
<?php if ($this->canEdit()) : ?>
    <a href="<?php echo $this->getEditUrl(); ?>" class="return link-reorder"><?php echo $this->__('Edit'); ?></a>
<?php endif; ?>
<h1><?php echo $this->getTitle(); ?></h1>
