<tfoot>
    <tr class="subtotal first">
        <td <?php echo 'colspan="'.$this->getColumns().'"';?> class="a-right">
            <?php echo $this->__('Subtotal :'); ?>
        </td>
        <td class="a-right">
            <span class="price"><?php echo $this->getGoodsTotal(); ?></span>
        </td>
    </tr>
    <tr class="shipping">     
        <td <?php echo 'colspan="'.$this->getColumns().'"';?> class="a-right">    
            <?php echo $this->__('Shipping  &amp; Handling :'); ?>
        </td>
        <td class="a-right">
            <span class="price"><?php echo $this->getCarriageAmount(); ?></span>
        </td>
    </tr>
    <tr>
        <td <?php echo 'colspan="'.$this->getColumns().'"';?> class="a-right">
            <?php echo $this->__('Tax :'); ?>
        </td>
        <td class="a-right">
            <span class="price"><?php echo $this->getTaxAmount(); ?></span>
        </td>
    </tr>
    <tr class="grand_total">
        <td <?php echo 'colspan="'.$this->getColumns().'"';?> class="a-right">
        <strong>
            <?php echo $this->__('Grand Total :'); ?>
        </strong></td>
        <td class="grand_total a-right">
            <strong><span class="price"><?php echo $this->getGrandTotal(); ?></span></strong>
        </td>
    </tr>
</tfoot>