<?php 
/* @var $this Epicor_BranchPickup_Block_Selectedbranch */

$branchpickupHelper = Mage::helper('epicor_branchpickup');
$_product = $this->getProduct();
/* @var $_product Epicor_Comm_Model_Product */
$_locations = $_product->getLocations();
$helper = Mage::helper('epicor_comm/locations');
/* @var $helper Epicor_Comm_Helper_Locations */
$allowed = $helper->getCustomerAllowedLocations();
$singleLocation = (count(array_intersect_key($_locations, $allowed)) <= 1);
?>
<?php if($branchpickupHelper->getSelectedBranch()): ?>
    <?php $selectedBranch = $this->getSelectedBranch($branchpickupHelper->getSelectedBranch()); ?>
    <?php $selectedBranchCode = $selectedBranch->getCode(); ?>
    <?php
    $locHelper = $this->helper('epicor_comm/locations');
    /* @var $helper Epicor_Comm_Helper_Locations */
    $currentStoreId = Mage::app()->getStore()->getStoreId();
    $relatedLocations = $this->getRelatedLocationsForProduct();
    $groupings = $this->getGroupings();
    $_groupLocations = array_column($groupings, 'locations');
    $aggregateStockLevels = Mage::registry('aggregate_stock_levels_'.$_product->getSku());

    $helperBranchPickup = Mage::helper('epicor_branchpickup/branchpickup');
    $url = Mage::getUrl('branchpickup/pickup/changepickuplocation', $helperBranchPickup->issecure());
    $cartPopupurl = Mage::getUrl('branchpickup/pickup/cartpopup', $helperBranchPickup->issecure());
    $selectbranch = Mage::getUrl('branchpickup/pickup/selectbranchajax', $helperBranchPickup->issecure());
    $commHelper = Mage::helper('epicor_comm');
    $decimalPlaces = $commHelper->getDecimalPlacesView(Mage::getResourceModel('catalog/product')->getAttributeRawValue($_product->getId(), 'decimal_places', Mage::app()->getStore()->getStoreId()));
    ?>
    <?php if (($_product->getTypeId() != 'grouped' && $_product->getTypeId() != 'configurable') && $helperBranchPickup->isValidBranch($selectedBranchCode)): ?>
        <div class="product_grid_locations" id="product_grid_locations">
            <div class="product_locations_wrapper selected_branch_wrapper" id="locations_list" style="display:none">
            <div style="clear:both">
                <p class="title"><strong><?php echo $this->__('Your Selected Branch') ?></strong></p>
                <div class="related-location-element">
                    <div class="location-element location-stock">
                        <?php if ($_product->isSaleable()) : ?>
                        <?php
                            switch ($_product->getStockType()):
                                case 'bool':
                        ?>
                                    <?php if ($_product->isAvailable()): ?>
                                        <p class="availability in-stock"><?php echo $this->__('Availability:') ?> <span><?php echo $this->__('In stock') ?></span></p>
                                    <?php else: ?>
                                        <p class="availability out-of-stock"><?php echo $this->__('Availability:') ?> <span><?php echo $this->__('Out of stock') ?></span></p>
                                    <?php endif; ?>
                                <?php break; ?> 
                                <?php case 'range': ?>
                                    <?php $_img = $_product->getStockRange(); ?>
                                    <img src="<?php echo $_img['src'] ?>" alt="<?php echo $_img['alt'] ?>" title="<?php echo $_img['title'] ?>" />        
                                <?php break; ?> 
                                <?php case 'level': ?>                                    
                                    <?php if ($selectedBranch->getShowInventory()): ?>
                                    <p class="availability in-stock"><?php echo $this->__('Stock:') ?> <span><?php echo $commHelper->truncateZero($_product->getStockLevel(),$decimalPlaces);  ?></span></p>
                                    <?php endif; ?>
                                <?php break; ?>         
                                    <?php endswitch; ?> 
                            <?php else: ?>
                                <p class="availability out-of-stock"><?php echo $this->__('Availability:') ?> <span><?php echo $this->__('Out of stock') ?></span></p>
                            <?php endif; ?>
                    </div>
                    <div class="location-element location-name">
                        <p><strong><?php echo $selectedBranch->getName(); ?></strong></p>
                        <p><?php echo $this->getBranchAddress($selectedBranch); ?></p>
                    </div>
                </div>
            </div>
            <?php if (!empty($relatedLocations) && (Mage::registry('rellocation_visibility_count_'.$_product->getId()) > 0) &&  !$singleLocation): ?>
                <!-- Related Locations Block --->
                <div style="clear:both">
                    <p class="title">
                        <?php $_relLocations = array_keys($relatedLocations); ?>
                        <?php $stock = Mage::helper('epicor_comm/locations')->aggregateLocationStockLevels($aggregateStockLevels, $_relLocations); ?>
                        <?php $stockClass = ($stock != 0) ? 'in-stock' : 'out-of-stock'; ?>
                        <?php if($stock != 0 && (Mage::registry('rellocation_showinventory_count_'.$_product->getId()) > 0)): ?><span class="aggregate-stock <?php echo $stockClass; ?>"><strong><?php echo $commHelper->truncateZero($stock, $decimalPlaces); ?></strong></span><?php endif; ?>
                        <strong><?php echo $this->__('Related Locations') ?></strong>
                    </p>
                    <div id="related_location_<?php echo $_product->getId(); ?>">
                    <?php foreach ($relatedLocations as $location): ?>
                        <?php if(!$location->getLocationVisible()): ?>
                            <?php continue; ?>
                        <?php endif; ?>
                        <div class="related-location-element">
                            <a id="link"  onclick="changeBranPickupLocation(this); return false;" href="<?php echo $location->getLocationCode(); ?>">
                                <input type="hidden" name="ajaxpickupbranchurl" id="ajaxpickupbranchurl" value="<?php echo $url; ?>" />
                                <input type="hidden" name="ajaxcode" id="ajaxcode" value="<?php echo $location->getLocationCode(); ?>" />
                                <input type="hidden" name="cartpopupurl" id="cartpopupurl" value="<?php echo $cartPopupurl; ?>" />
                                <input type="hidden" name="selectbranch" id="selectbranch" value="<?php echo $selectbranch; ?>" />
                                <?php $_product->setToLocationPrices($location); ?>
                                <div class="location-element location-stock">
                                    <?php if ($_product->isSaleable()) : ?>       
                                    <?php
                                        switch ($_product->getStockType()):
                                            case 'bool':
                                    ?>
                                            <?php if ($_product->isAvailable()): ?>
                                            <p class="availability in-stock"><?php echo $this->__('Availability:') ?> <span><?php echo $this->__('In stock') ?></span></p>
                                            <?php else: ?>
                                            <p class="availability out-of-stock"><?php echo $this->__('Availability:') ?> <span><?php echo $this->__('Out of stock') ?></span></p>
                                            <?php endif; ?>
                                            <?php break; ?> 
                                    <?php case 'range': ?>
                                        <?php $_img = $_product->getStockRange(); ?>
                                        <img src="<?php echo $_img['src'] ?>" alt="<?php echo $_img['alt'] ?>" title="<?php echo $_img['title'] ?>" />        
                                    <?php break; ?> 
                                    <?php case 'level': ?>
                                            <?php if($location->getShowInventory()): ?>
                                            <p class="availability in-stock"><?php echo $this->__('Stock:') ?> <span><?php echo $commHelper->truncateZero($aggregateStockLevels[$location->getLocationCode()], $decimalPlaces); ?></span></p>
                                            <?php endif; ?>
                                        <?php break; ?>         
                                        <?php endswitch; ?> 
                                    <?php else: ?>
                                        <p class="availability out-of-stock"><?php echo $this->__('Availability:') ?> <span><?php echo $this->__('Out of stock') ?></span></p>
                                    <?php endif; ?>
                                </div>
                                <div class="location-element location-name">
                                    <p><strong><?php echo $location->getName(); ?></strong></p>
                                    <p><?php echo $this->getBranchAddress($location); ?></p>
                                </div>
                                <div class="location-element location-select">
                                    <span><?php echo $this->__('Select'); ?></span>
                                </div>
                            </a>
                        </div>
                    <?php endforeach; ?>
                    </div>
                </div>
                <?php endif; ?>
                <?php if (!empty($_groupLocations) &&  !$singleLocation): ?>
                <!-- Location Grouping Block --->
                <?php foreach ($groupings as $groupName => $group): ?>
                    <?php if (isset($group['locations']) && !empty($group['locations']) && ($group['location_visibility_count'] > 0)): ?>
                        <?php $locations = $group['locations']; ?>
                        <?php $display = (isset($group['group_expandable']) && ($group['group_expandable'] == 1)) ? "display:none;": ""; ?>
                        <?php $event = (isset($group['group_expandable']) && ($group['group_expandable'] == 1)) ? "class='accordin' style='cursor:pointer;' onclick=toggleBlock('location_group_".$group['group_id']."_".$_product->getId()."')": ""; ?>
                        <div style="clear:both;">
                            <p <?php echo $event; ?>>
                                <?php $groupStockLocations = array_keys($locations); ?>
                                <?php if (isset($group['show_aggregate_stock']) && ($group['show_aggregate_stock'] == 1)): ?>
                                    <?php $stock = Mage::helper('epicor_comm/locations')->aggregateLocationStockLevels($aggregateStockLevels, $groupStockLocations); ?>
                                    <?php $stockClass = ($stock != 0) ? 'in-stock' : 'out-of-stock'; ?>
                                    <?php if($stock != 0 && ($group['location_showinventory_count'] > 0)): ?><span class="aggregate-stock <?php echo $stockClass; ?>"><strong><?php echo $commHelper->truncateZero($stock, $decimalPlaces); ?></strong></span><?php endif; ?>
                                <?php endif; ?>
                                <strong><?php echo $this->__($groupName) ?></strong>
                            </p>
                            <div style="<?php echo $display; ?>" id="location_group_<?php echo $group['group_id']; ?>_<?php echo $_product->getId(); ?>">
                                <?php foreach ($locations as $location): ?>
                                <?php if(!$location->getLocationVisible()): ?>
                                    <?php continue; ?>
                                <?php endif; ?>
                                <div class="related-location-element">
                                    <?php if($selectedBranchCode != $location->getLocationCode()): ?><a id="link"  onclick="changeBranPickupLocation(this); return false;" href="<?php echo $location->getLocationCode(); ?>"><?php endif; ?>
                                        <input type="hidden" name="ajaxpickupbranchurl" id="ajaxpickupbranchurl" value="<?php echo $url; ?>" />
                                        <input type="hidden" name="ajaxcode" id="ajaxcode" value="<?php echo $location->getLocationCode(); ?>" />
                                        <input type="hidden" name="cartpopupurl" id="cartpopupurl" value="<?php echo $cartPopupurl; ?>" />
                                        <input type="hidden" name="selectbranch" id="selectbranch" value="<?php echo $selectbranch; ?>" />
                                        <?php $_product->setToLocationPrices($location); ?>
                                        <div class="location-element location-stock">
                                            <?php if ($_product->isSaleable()) : ?>      
                                            <?php
                                                 switch ($_product->getStockType()):
                                                    case 'bool':
                                            ?>
                                                    <?php if ($_product->isAvailable()): ?>
                                                    <p class="availability in-stock"><?php echo $this->__('Availability:') ?> <span><?php echo $this->__('In stock') ?></span></p>
                                                    <?php else: ?>
                                                    <p class="availability out-of-stock"><?php echo $this->__('Availability:') ?> <span><?php echo $this->__('Out of stock') ?></span></p>
                                                    <?php endif; ?>
                                                    <?php break; ?> 
                                            <?php case 'range': ?>
                                                <?php $_img = $_product->getStockRange(); ?>
                                                <img src="<?php echo $_img['src'] ?>" alt="<?php echo $_img['alt'] ?>" title="<?php echo $_img['title'] ?>" />        
                                            <?php break; ?> 
                                            <?php case 'level': ?>
                                                <?php if($location->getShowInventory()): ?>
                                                    <p class="availability in-stock"><?php echo $this->__('Stock:') ?> <span><?php echo $commHelper->truncateZero($aggregateStockLevels[$location->getLocationCode()],$decimalPlaces); ?></span></p>
                                                <?php endif; ?>
                                                <?php break; ?>         
                                            <?php endswitch; ?> 
                                            <?php else: ?>
                                                <p class="availability out-of-stock"><?php echo $this->__('Availability:') ?> <span><?php echo $this->__('Out of stock') ?></span></p>
                                            <?php endif; ?>
                                        </div>
                                        <div class="location-element location-name">
                                            <p><strong><?php echo $location->getName(); ?></strong></p>
                                            <p><?php echo $this-> getBranchAddress($location); ?></p>
                                        </div>
                                        <?php if($selectedBranchCode != $location->getLocationCode()): ?>
                                        <div class="location-element location-select">
                                            <span><?php echo $this->__('Select'); ?></span>
                                        </div>
                                    </a>
                                        <?php endif; ?>
                                </div>
                                <?php endforeach; ?>
                            </div>
                        </div>
                    <?php endif; ?>
                <?php endforeach; ?>
		<?php endif; ?>
            </div>
        </div>
        <?php $this->resetProduct(); ?>
    <?php endif; ?>
<?php endif; ?>