<?php
/**
 * Edit customer address template
 *
 * @see Epicor_Comm_Block_Customer_Locationpicker
 * 
 *
 */
/* @var $this Epicor_Comm_Block_Customer_Locationpicker */
?> 
<?php if ($this->isAllowed()) : ?>
    <div class="block locations_filter_block" >
        <div class="block-title">
            <strong><span><?php echo $this->getTitle(); ?></span></strong>
        </div>
        <div class="block-content">
            <div class="empty">
                <form action="<?php echo $this->getFormUrl(); ?>" method="post">   
                    <ul class="locations_filter_list">
                        <li class="wide">
                            <label for="locations_filter" ><?php echo $this->__('Locations') ?></label>
                            <div class="input-box">
                                <select name="locations_filter[]" id="locations_filter" <?php if($this->canChooseMultipleLocations()):?>multiple="true"<?php endif; ?>>
                                    <?php foreach ($this->getCustomerAllowedLocations() as $code => $location): ?>
                                        <option value="<?php echo $code; ?>" <?php if($this->isLocationSelected($code)):?>selected="selected"<?php endif; ?>><?php echo $location->getName(); ?></option>
                                    <?php endforeach; ?>
                                </select>
                            </div>
                            <?php if($this->canChooseMultipleLocations()):?>
                            <p class="note sml-text"><?php echo $this->__('Choose one or more locations to filter by.') ?></p>    
                            <?php endif; ?>
                        </li>
                        <?php $groups = $this->getGroupLocations(); ?>
                        <?php if($groups->getSize() > 0): ?>
                        <?php $groupSelected = $this->isGroupSelected(true); ?>
                        <li class="wide">
                            <div class="input-box">
                                <label for="location_groups" ><?php echo $this->__('Location Groups') ?></label>
                                <select name="location_groups" id="location_groups">
                                    <option value=""><?php echo $this->__('-- No Selection --'); ?></option>
                                    <?php foreach ($groups as $group): ?>
                                    <option value="<?php echo $group->getId(); ?>" <?php if($groupSelected == $group->getId()): ?>selected="selected"<?php endif; ?>><?php echo $group->getGroupName(); ?></option>
                                    <?php endforeach; ?>
                                </select>
                            </div>
                        </li>
                        <?php endif; ?>
                    </ul>
                    <div class="buttons-set actions">
                        <input type="hidden" name="return_url" value="<?php echo $this->getReturnUrl(); ?>" />
                        <button type="submit" title="<?php echo $this->__('Filter Locations') ?>" class="button" ><span><span><?php echo $this->__('Filter Locations') ?></span></span></button>
                    </div>
                </form>
            </div>
        </div>
    </div>   
<?php endif; ?>
