<?php
/**
 * RFQ Address display
 * 
 * @category   Epicor
 * @package    Epicor_Customerconnect
 * @author     Epicor Websales Team
 */
/* @var $this Epicor_Customerconnect_Block_Customer_Rfqs_Details_Address */
?><div class='<?php echo $this->getOnRight() ? 'col-2 ' : 'col-1'; ?> box-info box-account'>
    <div class="box-head">
        <h2><?php echo $this->getTitle(); ?></h2>
    </div>
    <?php if (!empty($this->_addressData)) : ?>
        <?php if ($this->isEditable()) { ?>
            <div>
                <?php
                echo $this->getAddressesHtmlSelect();
                ?>
            </div>
        <?php } ?>
        <div id="<?php echo $this->getAddressType(); ?>-address-content">
            <?php if (!$this->isEditable() || $this->isErpAddress()): ?>

                <dl class="vcard">
                    <dt class="address hidden">Address</dt>
                    <?php if($this->getShowName()) : ?><dd class="first fn org"><?php echo $this->getName(); ?></dd><?php endif; ?>
                    <dd class="company org"><?php echo $this->getCompany(); ?></dd>
                    <dd class="adr break">
                        <span class="street-address"><?php echo $this->getStreet(); ?></span>
                        <span class="locality"><?php echo $this->getCity(); ?></span>
                        <span class="region"><?php echo $this->getCounty(); ?></span>
                        <span class="postal-code"><?php echo $this->getPostcode(); ?></span>
                        <span class="country-name"><?php echo $this->getCountry(); ?></span>
                    </dd>
                    <?php if ($this->_addressData->getEmailAddress()): ?>
                        <dt class="sec email"><abbr title="Email">Email</abbr> :</dt>
                        <dd class="sec email spaced"><?php echo $this->_addressData->getEmailAddress(); ?></dd>
                    <?php endif; ?>
                    <?php if ($this->getTelephoneNumber()): ?>
                        <dt class="sec tel"><abbr title="Telephone Number">T</abbr> :</dt>
                        <dd class="sec tel spaced"><?php echo $this->getTelephoneNumber(); ?></dd>
                    <?php elseif ($this->_addressData->getPhone()): ?>
                        <dt class="sec tel"><abbr title="Telephone Number">T</abbr> :</dt>
                        <dd class="sec tel spaced"><?php echo $this->_addressData->getPhone(); ?></dd>
                    <?php endif; ?>
                    <?php if ($this->getFaxNumber()): ?>
                        <dt class="sec fax"><abbr title="Fax Number">F</abbr> :</dt>
                        <dd class="sec fax spaced"><?php echo $this->getFaxNumber(); ?></dd>
                    <?php elseif ($this->_addressData->getFax()): ?>
                        <dt class="sec fax"><abbr title="Fax Number">F</abbr> :</dt>
                        <dd class="sec fax spaced"><?php echo $this->_addressData->getFax(); ?></dd>
                    <?php endif; ?>
                    <?php if ($this->getCarriageText()): ?>
                        <dt class="sec carriage"><?php echo $this->__('Instructions'); ?>: </dt>
                        <dd class="sec carriage spaced"><?php echo $this->getCarriageText(); ?></dd>
                    <?php endif; ?>
                </dl>
                <input type="hidden" name="<?php echo $this->getAddressType(); ?>_address[address_code]" value="<?php echo $this->_addressData->getAddressCode(); ?>" />
                <input type="hidden" name="<?php echo $this->getAddressType(); ?>_address[name]" value="<?php echo $this->_addressData->getName(); ?>" />
                <input type="hidden" name="<?php echo $this->getAddressType(); ?>_address[company]" value="<?php echo $this->_addressData->getCompany(); ?>" />
                <input type="hidden" name="<?php echo $this->getAddressType(); ?>_address[address1]" value="<?php echo $this->_addressData->getAddress1(); ?>" />
                <input type="hidden" name="<?php echo $this->getAddressType(); ?>_address[address2]" value="<?php echo $this->_addressData->getAddress2(); ?>" />
                <input type="hidden" name="<?php echo $this->getAddressType(); ?>_address[address3]" value="<?php echo $this->_addressData->getAddress3(); ?>" />
                <input type="hidden" name="<?php echo $this->getAddressType(); ?>_address[city]" value="<?php echo $this->_addressData->getCity(); ?>" />
                <input type="hidden" name="<?php echo $this->getAddressType(); ?>_address[county]" value="<?php echo $this->_addressData->getCounty(); ?>" />
                <input type="hidden" name="<?php echo $this->getAddressType(); ?>_address[country]" value="<?php echo $this->_addressData->getCountry(); ?>" />
                <input type="hidden" name="<?php echo $this->getAddressType(); ?>_address[postcode]" value="<?php echo $this->_addressData->getPostcode(); ?>" />
                <input type="hidden" name="<?php echo $this->getAddressType(); ?>_address[emailAddress]" value="<?php echo $this->_addressData->getEmailAddress(); ?>" />
                <input type="hidden" name="<?php echo $this->getAddressType(); ?>_address[instructions]" value="<?php echo $this->getCarriageText(); ?>" />

            <?php else: ?>
                <?php echo $this->getAddressesFormHtml(); ?>
            <?php endif; ?>
        </div>
    <?php endif; ?>
</div>

