<?php
$helper = Mage::helper('epicor_comm/configurator');
/* @var $helper Epicor_Comm_Helper_Configurator */
?>
<div id="messages" class="messages"></div>
<form id="rfq_update" target="rfq-form-iframe" name= "rfqform" action="<?php echo Mage::registry('rfq_new') ? Mage::getUrl('*/*/add/') : Mage::getUrl('*/*/update'); ?>" method="post" enctype="multipart/form-data">
    <!--<form id="rfq_update" target="rfq-form-iframe" name= "rfqform"  method="post" enctype="multipart/form-data">-->
    <input id="rfq_address_details" type="hidden" value="<?php echo Mage::getUrl('customerconnect/rfqs/addressdetails'); ?>" />
    <input id="rfq_ewa_returnurl" type="hidden" value="<?php echo base64_encode('customerconnect/rfqs/ewaeditcomplete'); ?>" />
    <input id="rfq_configurable_url" type="hidden" value="<?php echo Mage::getUrl('customerconnect/rfqs/configureproduct'); ?>" />
    <input id="currentStoreId" type="hidden" value="<?php echo Mage::app()->getStore()->getStoreId(); ?>" />
    <input id="rfq_ewa_cimurl" type="hidden" value="<?php echo Mage::getUrl('epicor_comm/message/cim'); ?>" />
    <input id="rfq_ewa_cdmurl" type="hidden" value="<?php echo Mage::getUrl('epicor_comm/message/cdm'); ?>" />
    <input id="rfq_ewa_show_basedesc" type="hidden" value="<?php echo $helper->getEwaDisplay('base_description') ? 'Y' : 'N'; ?>" />
    <input id="rfq_ewa_show_title" type="hidden" value="<?php echo $helper->getEwaDisplay('ewa_title') ? 'Y' : 'N'; ?>" />
    <input id="rfq_ewa_show_shortdesc" type="hidden" value="<?php echo $helper->getEwaDisplay('ewa_short_description') ? 'Y' : 'N'; ?>" />
    <input id="rfq_ewa_show_desc" type="hidden" value="<?php echo $helper->getEwaDisplay('ewa_description') ? 'Y' : 'N'; ?>" />
    <input id="rfq_ewa_show_sku" type="hidden" value="<?php echo $helper->getEwaDisplay('ewa_sku') ? 'Y' : 'N'; ?>" />
    <?php if (Mage::registry('rfq_new')) : ?>
        <input type="hidden" id="rfq_new" name="rfq_new" value="1" />
    <?php endif; ?>