<?php
/**
 * RFQ line search block
 * 
 * @category   Epicor
 * @package    Epicor_Customerconnect
 * @author     Epicor Websales Team
 */

/* @var $this Mage_Core_Block_Template */
?>
<div class="empty" id="line-search" style="display:none">
    <div class="box-head">
        <h2><?php echo $this->__('Search'); ?></h2>
    </div>
    <div class="formfields">
        <iframe id="linesearch-iframe"></iframe>
    </div>
    <div class="buttons-set actions buttonbar">
        <a id="line-search-close">Close</a>
    </div>
</div>