<?php
$product = Mage::registry('current_product');
/* @var $product Epicor_Comm_Model_Product */
?>
<form id="configure_product_form" action="<?php echo Mage::getUrl('*/*/submitconfiguration/'); ?>" method="post" enctype="multipart/form-data">
    <h2><?php echo $this->__('Configure Product %s', $product->getSku()); ?></h2>
    <p><?php echo $product->getShortDescription(); ?></p>   
    <?php
    /* @var $this Epicor_Customerconnect_Block_Customer_Rfqs_Details_Product_Configure */

    echo $this->getProductOptionsHtml();
    ?>
    <input type="hidden" name="productid" value="<?php echo $product->getId(); ?>"/>
    <input type="hidden" name="currency_code" value="<?php echo Mage::app()->getRequest()->getParam('currency_code'); ?>"/>
    <input type="hidden" name="qty" value="<?php echo Mage::app()->getRequest()->getParam('qty'); ?>"/>
    <div class="configurable_addtocart">  
        <?php $buttonTitle = $this->__('Submit'); ?>
        <?php $cButtonTitle = $this->__('Cancel'); ?>
        <br />
        <div class="add-to-cart">
            <button type="button" title="<?php echo $buttonTitle ?>" class="button btn-cart" onclick="" id="configure_product">
                <span><span><?php echo $buttonTitle; ?></span></span>
            </button>
            <button type="button" title="<?php echo $cButtonTitle ?>" class="button btn-cart" onclick="" id="cancel_configure_product">
                <span><span><?php echo $cButtonTitle; ?></span></span>
            </button>
        </div>
    </div>
</form>