
<h2><?php echo $this->__('An error occured while communicating to the product configurator.'); ?></h2>
<br />
<p><?php echo $this->__('The website has failed to connect to the product configurator. Please try again.'); ?></p>
<script type="text/javascript">
    <!--
        
    var message = {
        width: 575,
        height: 175
    };
    window.parent.postMessage(JSON.stringify(message), '*');

  -->
</script>