
<h2><?php echo $this->__('An error occured while communicating to the product configurator.'); ?></h2>
<br />
<p><?php echo $this->__('The product configurator requires 3rd party cookies to be allowed by your browser. Please enable 3rd party cookies and try again.'); ?></p>
<script type="text/javascript">
    <!--
        
    var message = {
        width: 575,
        height: 175
    };
    window.parent.postMessage(JSON.stringify(message), '*');

  -->
</script>