<?php
/**
 * Entity details page title
 * 
 * @category   Epicor
 * @package    Epicor_Customerconnect
 * @author     Epicor Websales Team
 */
/* @var $this Epicor_Customerconnect_Block_Customer_Title */
$postparams = Mage::App()->getRequest()->getParam('invoiceid');
$dispute = Mage::App()->getRequest()->getParam('dispute');
$disputeComment = Mage::App()->getRequest()->getParam('disputeComment');
?>
<div class="actions" style="  margin: 10px; padding-bottom: 42px;">       
    <button style="float:right" type="button" title="Close" class="button" onclick="arpayments.closepopup('<?php echo $postparams?>')"><span><span>Close</span></span></button>
</div>
<div style="padding: 10px">
<h1><?php echo $this->getTitle(); ?></h1>
