<?php
/**
 * Tracking popup override, adds extra data to custom tracking methods with urls
 *
 * @category   Epicor
 * @package    Epicor_Comm
 * @author     Epicor Websales Team
 */
?>
<?php /** @var $this Mage_Shipping_Block_Tracking_Popup */ ?>
<?php
    $helper = Mage::helper('customerconnect');
    /* @var $helper Epicor_Customerconnect_Helper_Data */ 
    $getGlobalUrl = $helper->getGlobalReturnUrl();
?>
<?php $_results = $this->getTrackingInfo(); ?>
<div class="page-title title-buttons">
    <h1><?php echo $this->__('Tracking Information'); ?></h1>
    <button class="button" onclick="window.close(); window.opener.focus();"><span><span><?php echo $this->__('Close Window') ?></span></span></button>
</div>
<?php if(sizeof($_results)>0): ?>
<?php foreach($_results as $shipid => $_result): ?>
    <?php if($shipid): ?>
    <h2 class="sub-title"><?php echo $this->__('Shipment #').$shipid; ?></h2>
    <?php endif; ?>
    <?php if(sizeof($_result)>0): ?>
        <?php $rowCount = sizeof($_result); $counter = 1; ?>
        <?php $_id = 0; foreach($_result as $track): ?>
            <table class="tracking-table-popup data-table" id="tracking-table-popup-<?php echo $_id ?>">
                <col width="15%" />
                <col />
                <tbody>
                <?php if(is_object($track)): ?>
                    <tr>
                        <th class="label"><?php echo $this->__('Tracking Number:'); ?></th>
                        <td class="value"><?php echo $this->escapeHtml($track->getTracking()); ?></td>
                    </tr>
                    <?php if ($track->getCarrierTitle()): ?>
                    <tr>
                        <th class="label"><?php echo $this->__('Carrier:'); ?></th>
                        <td class="value"><?php echo $this->escapeHtml($track->getCarrierTitle()); ?></td>
                    </tr>
                    <?php endif; ?>
                    <?php if($track->getErrorMessage()): ?>
                    <tr>
                        <th class="label"><?php echo $this->__('Error:'); ?></th>
                        <td class="error"><?php echo $this->__('Tracking information is currently not available. Please '); if ($this->getContactUsEnabled()) : ?><a href="<?php echo $this->getContactUs() ?>" title="<?php echo $this->__('contact us') ?>" onclick="this.target='_blank'"><?php echo $this->__('contact us') ?></a><?php echo $this->__(' for more information or '); endif; echo $this->__('email us at '); ?><a href="mailto:<?php echo $this->getStoreSupportEmail() ?>"><?php echo $this->getStoreSupportEmail() ?></a></td>
                    </tr>
                    <?php elseif($track->getTrackSummary()): ?>
                    <tr>
                        <th class="label"><?php echo $this->__('Info:'); ?></th>
                        <td class="value"><?php echo $track->getTrackSummary(); ?></td>
                    </tr>
                    <?php elseif($track->getUrl()): ?>
                    <tr>
                        <th class="label"><?php echo $this->__('Track:'); ?></th>
                        <td class="value"><a href="<?php echo $this->escapeHtml($track->getUrl()); ?>" onclick="this.target='_blank'"><?php echo $this->escapeHtml($track->getUrl()); ?></a></td>
                    </tr>
                    <?php else: ?>
                        <?php if ($track->getStatus()): ?>
                        <tr>
                            <th class="label"><?php echo $this->__('Status:'); ?></th>
                            <td class="value"><?php echo $track->getStatus(); ?></td>
                        </tr>
                        <?php endif; ?>

                        <?php if ($track->getDeliverydate()): ?>
                        <tr>
                            <th class="label"><?php echo $this->__('Delivered on:'); ?></th>
                            <td class="value"><?php echo $this->formatDeliveryDateTime($track->getDeliverydate(),$track->getDeliverytime()); ?></td>
                        </tr>
                        <?php endif; ?>

                        <?php if ($track->getSignedby()): ?>
                        <tr>
                            <th class="label"><?php echo $this->__('Signed by:'); ?></th>
                            <td class="value"><?php echo $track->getSignedby(); ?></td>
                        </tr>
                        <?php endif; ?>

                        <?php if ($track->getDeliveryLocation()): ?>
                        <tr>
                            <th class="label"><?php echo $this->__('Delivered to:'); ?></th>
                            <td class="value"><?php echo $track->getDeliveryLocation(); ?></td>
                        </tr>
                        <?php endif; ?>

                        <?php if ($track->getShippedDate()): ?>
                        <tr>
                            <th class="label"><?php echo $this->__('Shipped or billed on:'); ?></th>
                            <td class="value"><?php echo $track->getShippedDate(); ?></td>
                        </tr>
                        <?php endif; ?>

                        <?php if ($track->getService()): ?>
                        <tr>
                            <th class="label"><?php echo $this->__('Service Type:'); ?></th>
                            <td class="value"><?php echo $track->getService(); ?></td>
                        </tr>
                        <?php endif; ?>

                        <?php if ($track->getWeight()): ?>
                        <tr>
                            <th class="label"><?php echo $this->__('Weight:'); ?></th>
                            <td class="value"><?php echo $track->getWeight(); ?></td>
                        </tr>
                        <?php endif; ?>
                    <tr style="border:0px !important">
                        <th class="" style="border:0px !important;background: none"></th>
                        <td style="border:0px !important"></td>
                    </tr>                          
                    <?php endif; ?>
                <?php elseif(isset($track['title']) && isset($track['number']) && $track['number']): ?>
                    <!--if the tracking is custom value-->
                    <?php
                     if(!empty($track['carrier_code'])) :
                        $methodMode   = $helper->getMappingShippingCode($track['carrier_code']);
                        $methodCode  = $methodMode['method'];
                        $methodUrl   = $methodMode['methodurl'];    
                        if($methodCode) {
                           $shipment = $methodCode;  
                           $track['title'] = $methodCode;
                        }
                        if($methodCode && $methodUrl && $track['track_number'] && !$track['url']) {
                           $trackingMethodUrl = $helper->formatTrackingUrl($methodUrl,$track['track_number']); 
                           $track['url']   = $trackingMethodUrl;
                           $track['title'] = $methodCode;
                        }                        
                      endif;   
                    ?>
                    <tr>
                        <th class="label"><?php echo $this->__('Tracking Number:'); ?></th>
                        <td class="value"><?php echo $this->escapeHtml($track['number']); ?></td>
                    </tr>
                    <?php if(!empty($methodCode) && !empty($track['carrier_code'])) : ?>
                    <tr>
                        <th class="label"><?php echo $this->__('Method:'); ?></th>
                        <td class="value"><?php echo $this->escapeHtml($methodCode); ?></td>
                    </tr>                    
                    <?php endif; ?>
                    <?php if(isset($track['url']) && !empty($track['url'])) : ?>
                    <tr>
                        <th class="label"><?php echo $this->__('Track:'); ?></th>
                        <td class="value"><a href="<?php echo $this->escapeHtml($track['url']); ?>" onclick="this.target='_blank'"><?php echo $this->escapeHtml($track['url']); ?></a></td>
                    </tr>
                    <?php endif; ?>
                    <?php if((empty($track['url'])) && (!empty($track['number'])) && (!empty($getGlobalUrl))) : ?>
                    <tr>
                        <th class="label"><?php echo $this->__('Track:'); ?></th>
                        <?php $trackingUrls = $helper->formatTrackingUrl($getGlobalUrl,$track['number']); ?>
                        <td class="value"><a href="<?php echo $this->escapeHtml($trackingUrls); ?>" onclick="this.target='_blank'"><?php echo $this->escapeHtml($trackingUrls); ?></a></td>
                    </tr>
                    <?php endif; ?>                    
                    <tr>
                        <th class="label"><?php echo $this->__('Shipment For:'); ?></th>
                        <td class="value"><?php echo nl2br($this->escapeHtml($track['description'])); ?></td>
                    </tr>
                    <tr style="border:0px !important">
                        <th class="" style="border:0px !important;background: none"></th>
                        <td style="border:0px !important"></td>
                    </tr>                      

                    
                    <?php elseif(isset($track['title']) && (!$track['number']) && !$track['number']): ?>
                    <!--if the tracking is custom value-->
                    <?php
                     if(!empty($track['carrier_code'])) :
                        $methodMode   = $helper->getMappingShippingCode($track['carrier_code']);
                        $methodCode  = $methodMode['method'];
                        $methodUrl   = $methodMode['methodurl'];    
                        if($methodCode) {
                           $shipment = $methodCode;  
                           $track['title'] = $methodCode;
                        }
                        if($methodCode && $methodUrl && $track['track_number'] && !$track['url']) {
                           $trackingMethodUrl = $helper->formatTrackingUrl($methodUrl,$track['track_number']); 
                           $track['url']   = $trackingMethodUrl;
                           $track['title'] = $methodCode;
                        }                        
                      endif;   
                    ?>
                    <?php if(!empty($methodCode) && !empty($track['carrier_code'])) : ?>
                    <tr>
                        <th class="label"><?php echo $this->__('Method:'); ?></th>
                        <td class="value"><?php echo $this->escapeHtml($methodCode); ?></td>
                    </tr>                    
                    <?php endif; ?>
                    <tr>
                        <th class="label"><?php echo $this->__('Shipment For:'); ?></th>
                        <td class="value"><?php echo nl2br($this->escapeHtml($track['description'])); ?></td>
                    </tr>
                    <tr style="border:0px !important">
                        <th class="" style="border:0px !important;background: none"></th>
                        <td style="border:0px !important"></td>
                    </tr>                    
                <?php endif; ?>
                </tbody>
            </table>
            <script type="text/javascript">decorateTable('tracking-table-popup-<?php echo $_id++ ?>');</script>
            <?php if (is_object($track) && sizeof($track->getProgressdetail())>0): ?>
                <br />
                <table class="data-table" id="track-history-table-<?php echo $track->getTracking(); ?>">
                    <col />
                    <col width="1" />
                    <col width="1" />
                    <col />
                    <thead>
                        <tr>
                            <th><?php echo $this->__('Location') ?></th>
                            <th><?php echo $this->__('Date') ?></th>
                            <th><?php echo $this->__('Local Time') ?></th>
                            <th><?php echo $this->__('Description') ?></th>
                        </tr>
                   </thead>
                   <tbody>
                   <?php foreach($track->getProgressdetail() as $_detail): ?>
                    <?php $_detailDate = (isset($_detail['deliverydate']) ? $this->formatDeliveryDate($_detail['deliverydate']) : '') ?>
                    <?php $_detailTime = (isset($_detail['deliverytime']) ? $this->formatDeliveryTime($_detail['deliverytime'], $_detail['deliverydate']) : '') ?>
                        <tr>
                            <td><?php echo (isset($_detail['deliverylocation']) ? $_detail['deliverylocation'] : ''); ?></td>
                            <td><span class="nobr"><?php echo $_detailDate ?></span></td>
                            <td><span class="nobr"><?php echo $_detailTime ?></span></td>
                            <td><?php echo (isset($_detail['activity']) ? $_detail['activity'] : '') ?></td>
                        </tr>
                   <?php endforeach; ?>
                   </tbody>
                </table>
                <script type="text/javascript">decorateTable('track-history-table-<?php echo $track->getTracking(); ?>');</script>
            <?php endif; ?>
            <div class="divider"></div>
            <?php if($counter!=$rowCount): ?>
            <?php endif; ?>
            <?php $counter++; ?>
        <!--end for each tracking information-->
        <?php endforeach; ?>
    <?php else: ?>
        <p><?php echo $this->__('There is no tracking available for this shipment.'); ?></p>
    <?php endif; ?>

<?php endforeach; ?>
<?php else: ?>
    <p><?php echo $this->__('There is no tracking available.'); ?></p>
<?php endif; ?>
<div class="buttons-set">
    <button type="button" title="<?php echo $this->__('Close Window') ?>" class="button" onclick="window.close(); window.opener.focus();"><span><span><?php echo $this->__('Close Window') ?></span></span></button>
</div>
