<?php
/* @var $this Epicor_Common_Block_Adminhtml_Advanced_Syslog_View */
?>
<div class="entry-edit" >
    <div class="entry-edit-head">
        <h4>Log File Details</h4>
    </div>
    <fieldset id="order_erp_status_form">
        <table cellspacing="0" class="form-list">
            <tr>
                <td class="label"><label><?php echo Mage::helper('adminhtml')->__('File Name') ?></label></td>
                <td class="value"><strong><?php echo $this->getFilename(); ?></strong></td>
            </tr>
            <tr>
                <td class="label"><label><?php echo Mage::helper('adminhtml')->__('Last Modified') ?></label></td>
                <td class="value"><strong><?php echo $this->getFiledate(); ?></strong></td>
            </tr>
        </table>
    </fieldset>
    <div class="log_view">
        <?php
        if (substr($this->getFilepath(), -2) == 'gz'):
            $handle = gzopen($this->getFilepath(), 'rb');
            while (!gzeof($handle)) :
                echo nl2br(gzread($handle, 4096), true);
            endwhile;
            fclose($handle);
        else:
            $handle = fopen($this->getFilepath(), 'rb');
            while (!feof($handle)) :
                echo nl2br(fread($handle, 4096), true);
            endwhile;
            fclose($handle);
        endif;
        ?>
    </div>
</div>
